<?php 

/**
 * Joomla! 1.5 component s3manager
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_s3manager
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


jimport( 'joomla.application.component.controller' );
require_once( JPATH_COMPONENT.DS.'helpers'.DS.'helper.php' );
/**
 * S3Manager Controller
 *
 * @package S3Manager
 */
class S3ManagerController extends JController
{
	function __construct()
	{
		parent::__construct();
	}

	function display( )
	{
		parent::display();
	}
	function save()
	{
		$link = 'index.php?option=com_s3manager';
		$db = JFactory::getDBO();
		$this->setRedirect( $link, $this->msg);

	}

	function cancel()
	{
		$this->setRedirect( 'index.php?option=com_s3manager' );
	}

}

