<?php 

/**
 * Joomla! 1.5 component s3manager
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_s3manager
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
jimport('joomla.application.router');


?>
<?php JHTML::_('behavior.tooltip'); ?>
<?php
  // Set toolbar items for the page
  JToolBarHelper::title('Amazon Simple Storage Service', 's3manager_title');
  JToolBarHelper::save();
  JToolBarHelper::cancel();
  JToolBarHelper::preferences('com_s3manager', '400');
  $document =& JFactory::getDocument();
  $document->addStyleSheet(JURI::base(true) . '/components/com_s3manager/assets/icon.css', 'text/css', null, array());

  ?>
<form action="index.php" method="post" name="adminForm">
<input type="hidden" name="option" value="com_s3manager" />
<input type="hidden" name="task" value="" />

<?php if($this->login_failed) {
	?>
<h2 style="color:red">SalesForce login failed</h2>
<p>Please go to Parameters and set proper administrator account credentials.</p>
<p>Error details: <pre><?=htmlspecialchars($this->login_error) ?></pre></p>
<?php
} else {
	?>
		wow.
<?php
} // login_failed
?>
</form>
<p class="copyright">Amazon Simple Storage Service integration &copy; by <a href="http://cloudaccess.net">CloudAccess.net</a></p>
